module PfrpgTables::Tables::Heroclasses
end

require "pfrpg_tables/tables/heroclasses/alchemist"
require "pfrpg_tables/tables/heroclasses/arcane_archer"
require "pfrpg_tables/tables/heroclasses/arcane_trickster"
require "pfrpg_tables/tables/heroclasses/assassin"
require "pfrpg_tables/tables/heroclasses/barbarian"
require "pfrpg_tables/tables/heroclasses/bard"
require "pfrpg_tables/tables/heroclasses/cleric"
require "pfrpg_tables/tables/heroclasses/dragon_disciple"
require "pfrpg_tables/tables/heroclasses/druid"
require "pfrpg_tables/tables/heroclasses/duelist"
require "pfrpg_tables/tables/heroclasses/eldritch_knight"
require "pfrpg_tables/tables/heroclasses/fighter"
require "pfrpg_tables/tables/heroclasses/loremaster"
require "pfrpg_tables/tables/heroclasses/monk"
require "pfrpg_tables/tables/heroclasses/mystic_theurge"
require "pfrpg_tables/tables/heroclasses/paladin"
require "pfrpg_tables/tables/heroclasses/pathfinder_chronicler"
require "pfrpg_tables/tables/heroclasses/ranger"
require "pfrpg_tables/tables/heroclasses/rogue"
require "pfrpg_tables/tables/heroclasses/shadowdancer"
require "pfrpg_tables/tables/heroclasses/sorcerer"
require "pfrpg_tables/tables/heroclasses/wizard"